# Generated by Django 3.1 on 2020-08-30 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateField()),
                ('time2complete', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UnavailableTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unavailableTimeStart', models.IntegerField()),
                ('unavailableTimeEnd', models.IntegerField()),
            ],
        ),
    ]
