# Generated by Django 3.1 on 2020-08-30 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unavailabletime',
            name='unavailableTimeEnd',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='unavailabletime',
            name='unavailableTimeStart',
            field=models.TimeField(),
        ),
    ]
